spring:
  datasource:
    url: jdbc:mysql://123.60.75.90:3306/privilege?serverTimezone=UTC
    username: root
    password: XMUwwf@4288
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: XMUwwf@4288
    host: 121.37.149.40

server:
  port: 8012
mybatis:
  type-aliases-package: cn.edu.xmu.wwf.privilege # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true
jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "qwertyuiop7418520" #密钥
  expireTime: 1 #token有效时间 (分钟) 建议一小时以上:



