spring:
  datasource:
    url: jdbc:mysql://123.60.75.90:3306/privilege?serverTimezone=UTC
    username: root
    password: XMUwwf@4288
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8012
mybatis:
  type-aliases-package: cn.edu.xmu.wwf.privilege # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件
  configuration:
    map-underscore-to-camel-case: true
